#!/usr/bin/env ruby
# Run HTMLProofer via Ruby so we can do advanced things like ignore bad peer certificates which turn
# up in external links.
require 'html-proofer'
require 'optparse'
require 'jekyll'

proofer_options = { ignore_urls: [%r{\Ahttps://github.com/GSA-TTS/identity-dev-docs/edit}] }
OptionParser.new do |opt|
  opt.on('--internal') { proofer_options[:disable_external] = true }
  opt.on('--external') { proofer_options[:external_only] = true }
  opt.on('--url-ignore PATTERN') { |pattern| proofer_options[:ignore_urls] << /#{Regexp.quote(pattern)}/ }
  opt.on('--allow-hash-href') { proofer_options[:allow_hash_href] = true }
  opt.on('--disallow-hash-href') { proofer_options[:allow_hash_href] = false }
end.parse!

site_config = Jekyll::Configuration.from(YAML.load_file('_config.yml'))

proofer_options.merge!(
  allow_hash_href: true,
  empty_alt_ignore: true,
  typhoeus: {
    ssl_verifypeer: false,
    ssl_verifyhost: 0,
    followlocation: false
  },
  swap_urls: {
    "http://localhost:#{site_config['port']}" => 'https://developers.login.gov'
  }
)

proofer = HTMLProofer.check_directory(site_config['destination'], proofer_options)
proofer.before_request do |request|
  # Counter-intuitively, followlocation is set as false in the configuration and always reverted
  # to true before a request. External URL requests should be allowed to follow redirects, but
  # internal link trailing slash check is based on the raw options object.
  request.options[:followlocation] = true

  # Some URLs behave differently if `accept-language` header is not included. Remove this in the
  # future if it's no longer needed.
  request.options[:headers]['Accept-Language'] = '*'
end

proofer.run
